//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoAplikacija.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinoAplikacija.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema Application.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Date.
        /// </summary>
        internal static string BillDateLabel {
            get {
                return ResourceManager.GetString("BillDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILL.
        /// </summary>
        internal static string BillHtml {
            get {
                return ResourceManager.GetString("BillHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Information.
        /// </summary>
        internal static string BillInfoFormText {
            get {
                return ResourceManager.GetString("BillInfoFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Number.
        /// </summary>
        internal static string BillNumberLabel {
            get {
                return ResourceManager.GetString("BillNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills and Reservations.
        /// </summary>
        internal static string BillsReservationsLabel {
            get {
                return ResourceManager.GetString("BillsReservationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILL TO:.
        /// </summary>
        internal static string BillToHtml {
            get {
                return ResourceManager.GetString("BillToHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        internal static string BillTranslate {
            get {
                return ResourceManager.GetString("BillTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string BirthdayLabel {
            get {
                return ResourceManager.GetString("BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you forgot your password. We sent you the security code you&apos;ll need to reset it..
        /// </summary>
        internal static string BodyTextEmail {
            get {
                return ResourceManager.GetString("BodyTextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string CheckoutButton {
            get {
                return ResourceManager.GetString("CheckoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string CheckoutFormText {
            get {
                return ResourceManager.GetString("CheckoutFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Seats.
        /// </summary>
        internal static string ChooseSeatsWindowName {
            get {
                return ResourceManager.GetString("ChooseSeatsWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ColumnDate {
            get {
                return ResourceManager.GetString("ColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ColumnDateHtml {
            get {
                return ResourceManager.GetString("ColumnDateHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string ColumnEventHtml {
            get {
                return ResourceManager.GetString("ColumnEventHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Number.
        /// </summary>
        internal static string ColumnEventId {
            get {
                return ResourceManager.GetString("ColumnEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string ColumnMovieHtml {
            get {
                return ResourceManager.GetString("ColumnMovieHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Title.
        /// </summary>
        internal static string ColumnMovieTitle {
            get {
                return ResourceManager.GetString("ColumnMovieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Seats.
        /// </summary>
        internal static string ColumnNumberOfSeats {
            get {
                return ResourceManager.GetString("ColumnNumberOfSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Seat.
        /// </summary>
        internal static string ColumnPriceForOne {
            get {
                return ResourceManager.GetString("ColumnPriceForOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string ColumnQuantityHtml {
            get {
                return ResourceManager.GetString("ColumnQuantityHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat Numbers.
        /// </summary>
        internal static string ColumnSeatNumbers {
            get {
                return ResourceManager.GetString("ColumnSeatNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat Numbers.
        /// </summary>
        internal static string ColumnSeatNumbersHtml {
            get {
                return ResourceManager.GetString("ColumnSeatNumbersHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema Address.
        /// </summary>
        internal static string ColumnTheaterAddress {
            get {
                return ResourceManager.GetString("ColumnTheaterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater Address.
        /// </summary>
        internal static string ColumnTheaterAddressHtml {
            get {
                return ResourceManager.GetString("ColumnTheaterAddressHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater &amp; Room.
        /// </summary>
        internal static string ColumnTheaterRoom {
            get {
                return ResourceManager.GetString("ColumnTheaterRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater &amp; Room.
        /// </summary>
        internal static string ColumnTheaterRoomHtml {
            get {
                return ResourceManager.GetString("ColumnTheaterRoomHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ColumnTime {
            get {
                return ResourceManager.GetString("ColumnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string ColumnTimeHtml {
            get {
                return ResourceManager.GetString("ColumnTimeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string ColumnTotalHtml {
            get {
                return ResourceManager.GetString("ColumnTotalHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string ColumnTotalPrice {
            get {
                return ResourceManager.GetString("ColumnTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string ColumnUnitPriceHtml {
            get {
                return ResourceManager.GetString("ColumnUnitPriceHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Bill:.
        /// </summary>
        internal static string DateOfBillHtml {
            get {
                return ResourceManager.GetString("DateOfBillHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Payment:.
        /// </summary>
        internal static string DateOfPaymentHtml {
            get {
                return ResourceManager.GetString("DateOfPaymentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOUNT.
        /// </summary>
        internal static string DiscountHtml {
            get {
                return ResourceManager.GetString("DiscountHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string DiscountLabel {
            get {
                return ResourceManager.GetString("DiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string DiscountTranslate {
            get {
                return ResourceManager.GetString("DiscountTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code -.
        /// </summary>
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format..
        /// </summary>
        internal static string ErrorEmailFormat {
            get {
                return ResourceManager.GetString("ErrorEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Telephone number already exists..
        /// </summary>
        internal static string ErrorEmailTelephoneTaken {
            get {
                return ResourceManager.GetString("ErrorEmailTelephoneTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out..
        /// </summary>
        internal static string ErrorFillOut {
            get {
                return ResourceManager.GetString("ErrorFillOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Password..
        /// </summary>
        internal static string ErrorInputPassword {
            get {
                return ResourceManager.GetString("ErrorInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place with that ID does NOT exist..
        /// </summary>
        internal static string ErrorPlace {
            get {
                return ResourceManager.GetString("ErrorPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Security Code or the Time expired..
        /// </summary>
        internal static string ErrorSecurityCodeTime {
            get {
                return ResourceManager.GetString("ErrorSecurityCodeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a seat..
        /// </summary>
        internal static string ErrorSelectSeat {
            get {
                return ResourceManager.GetString("ErrorSelectSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong telephone number format..
        /// </summary>
        internal static string ErrorTelephoneNumberFormat {
            get {
                return ResourceManager.GetString("ErrorTelephoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with that email does not exist..
        /// </summary>
        internal static string ErrorUserExist {
            get {
                return ResourceManager.GetString("ErrorUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email address or password..
        /// </summary>
        internal static string ErrorWrongEmailPassword {
            get {
                return ResourceManager.GetString("ErrorWrongEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong telephone number or password..
        /// </summary>
        internal static string ErrorWrongTelephonePassword {
            get {
                return ResourceManager.GetString("ErrorWrongTelephonePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EventsButton {
            get {
                return ResourceManager.GetString("EventsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EventsLabel {
            get {
                return ResourceManager.GetString("EventsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileTranslate {
            get {
                return ResourceManager.GetString("FileTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice was created on a computer and is valid without the signature and seal..
        /// </summary>
        internal static string FooterHtml {
            get {
                return ResourceManager.GetString("FooterHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget your password?.
        /// </summary>
        internal static string ForgetPasswordLinkLabel {
            get {
                return ResourceManager.GetString("ForgetPasswordLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        internal static string HelloEmail {
            get {
                return ResourceManager.GetString("HelloEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_export_pdf_filled_80 {
            get {
                object obj = ResourceManager.GetObject("icons8-export-pdf-filled-80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string ItemsLabel {
            get {
                return ResourceManager.GetString("ItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitleLabel {
            get {
                return ResourceManager.GetString("LoginTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Payment..
        /// </summary>
        internal static string paidDateLabelNotPaid {
            get {
                return ResourceManager.GetString("paidDateLabelNotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid On:.
        /// </summary>
        internal static string paidDateLabelPaid {
            get {
                return ResourceManager.GetString("paidDateLabelPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string PasswordChangeButton {
            get {
                return ResourceManager.GetString("PasswordChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        internal static string PasswordResetFormText {
            get {
                return ResourceManager.GetString("PasswordResetFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Date.
        /// </summary>
        internal static string PayDateInfoLabel {
            get {
                return ResourceManager.GetString("PayDateInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please copy the.
        /// </summary>
        internal static string PleaseCopyEmail {
            get {
                return ResourceManager.GetString("PleaseCopyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE AFTER DISCOUNT.
        /// </summary>
        internal static string PriceAfterDiscountHtml {
            get {
                return ResourceManager.GetString("PriceAfterDiscountHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price After Discount.
        /// </summary>
        internal static string PriceAfterDiscountLabel {
            get {
                return ResourceManager.GetString("PriceAfterDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileButton {
            get {
                return ResourceManager.GetString("ProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills, Reservations.
        /// </summary>
        internal static string ReservationsBillsButton {
            get {
                return ResourceManager.GetString("ReservationsBillsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Reservation.
        /// </summary>
        internal static string ReserveButton {
            get {
                return ResourceManager.GetString("ReserveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security code.
        /// </summary>
        internal static string SecurityCodeEmail {
            get {
                return ResourceManager.GetString("SecurityCodeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string ShoppingCartLabel {
            get {
                return ResourceManager.GetString("ShoppingCartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpTitleLabel {
            get {
                return ResourceManager.GetString("SignUpTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate Payment.
        /// </summary>
        internal static string SimulatePaymentButton {
            get {
                return ResourceManager.GetString("SimulatePaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Stage1Button {
            get {
                return ResourceManager.GetString("Stage1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A security code will be sent to your email..
        /// </summary>
        internal static string Stage1HelpLabel {
            get {
                return ResourceManager.GetString("Stage1HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Stage2Button {
            get {
                return ResourceManager.GetString("Stage2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press continue when you recieve the security code..
        /// </summary>
        internal static string Stage2HelpLabel {
            get {
                return ResourceManager.GetString("Stage2HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Stage3Button {
            get {
                return ResourceManager.GetString("Stage3Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your security code..
        /// </summary>
        internal static string Stage3HelpLabel {
            get {
                return ResourceManager.GetString("Stage3HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        internal static string Stage3TextboxLabel {
            get {
                return ResourceManager.GetString("Stage3TextboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Stage4Button {
            get {
                return ResourceManager.GetString("Stage4Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password..
        /// </summary>
        internal static string Stage4HelpLabel {
            get {
                return ResourceManager.GetString("Stage4HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        internal static string SuccessPasswordReset {
            get {
                return ResourceManager.GetString("SuccessPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Signed Up!.
        /// </summary>
        internal static string SuccessSignUp {
            get {
                return ResourceManager.GetString("SuccessSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        internal static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        internal static string TelephoneNumberLabel {
            get {
                return ResourceManager.GetString("TelephoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number or email.
        /// </summary>
        internal static string TelephoneOrEmailLabel {
            get {
                return ResourceManager.GetString("TelephoneOrEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PRICE.
        /// </summary>
        internal static string TotalPriceHtml {
            get {
                return ResourceManager.GetString("TotalPriceHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and use it where it&apos;s requested..
        /// </summary>
        internal static string UseItEmail {
            get {
                return ResourceManager.GetString("UseItEmail", resourceCulture);
            }
        }
    }
}
